export const SAVE_VMUUID_REQUEST = 'SAVE_VMUUID_REQUEST';
export const SAVE_VMUUID = 'SAVE_VMUUID';

export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_FAILED = 'FETCH_CATEGORIES_FAILED';

export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAILED = 'FETCH_PRODUCTS_FAILED';

export const ADD_PRODUCT = 'ADD_PRODUCT';
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';
export const ADD_PRODUCT_FAILED = 'ADD_PRODUCT_FAILED';

export const REMOVE_PRODUCT = 'REMOVE_PRODUCT';
export const REMOVE_PRODUCT_SUCCESS = 'REMOVE_PRODUCT_SUCCESS';
export const REMOVE_PRODUCT_FAILED = 'REMOVE_PRODUCT_FAILED';

export const FETCH_PRODUCT_DETAIL = 'FETCH_PRODUCT_DETAIL';
export const FETCH_PRODUCT_DETAIL_SUCCESS = 'FETCH_PRODUCT_DETAIL_SUCCESS';
export const FETCH_PRODUCT_DETAIL_FAILED = 'FETCH_PRODUCT_DETAIL_FAILED';

export const VALIDATE_VENDING_MACHINE = 'VALIDATE_VENDING_MACHINE';
export const VALIDATE_VENDING_MACHINE_SUCCESS = 'VALIDATE_VENDING_MACHINE_SUCCESS';
export const VALIDATE_VENDING_MACHINE_FAILED = 'VALIDATE_VENDING_MACHINE_FAILED';

export const FETCH_PAYMENT_METHODS = 'FETCH_PAYMENT_METHODS';
export const FETCH_PAYMENT_METHODS_SUCCESS = 'FETCH_PAYMENT_METHODS_SUCCESS';
export const FETCH_PAYMENT_METHODS_FAILED = 'FETCH_PAYMENT_METHODS_FAILED';

export const REQUEST_GET_CHARGE_OBJECT = 'REQUEST_GET_CHARGE_OBJECT';
export const REQUEST_GET_CHARGE_OBJECT_SUCCESS = 'REQUEST_GET_CHARGE_OBJECT_SUCCESS';
export const REQUEST_GET_CHARGE_OBJECT_FAILED = 'REQUEST_GET_CHARGE_OBJECT_FAILED';

export const FINALIZE_PAYMENT = 'FINALIZE_PAYMENT';
export const CLEAN_CART = 'CLEAN_CART';
