export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_FAILED = 'FETCH_CATEGORIES_FAILED';

export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAILED = 'FETCH_PRODUCTS_FAILED';

export const FETCH_PRODUCTS_BY_CATEGORIES = 'FETCH_PRODUCTS_BY_CATEGORIES';
export const FETCH_PRODUCTS_BY_CATEGORIES_APPEND =
  'FETCH_PRODUCTS_BY_CATEGORIES_APPEND';
export const FETCH_PRODUCTS_BY_CATEGORIES_SUCCESS =
  'FETCH_PRODUCTS_BY_CATEGORIES_SUCCESS';
export const FETCH_PRODUCTS_BY_CATEGORIES_FAILED =
  'FETCH_PRODUCTS_BY_CATEGORIES_FAILED';

export const REQUEST_LOGIN = 'REQUEST_LOGIN';
export const REQUEST_LOGIN_SUCCESS = 'REQUEST_LOGIN_SUCCESS';
export const REQUEST_LOGIN_FAILED = 'REQUEST_LOGIN_FAILED';

export const CHECK_AUTHORIZED = 'CHECK_AUTHORIZED';
export const CHECK_AUTHORIZED_SUCCESS = 'CHECK_AUTHORIZED_SUCCESS';
export const CHECK_AUTHORIZED_FAILED = 'CHECK_AUTHORIZED_FAILED';

export const FETCH_ORDER_LIST = 'FETCH_ORDER_LIST';
export const FETCH_ORDER_LIST_SUCCESS = 'FETCH_ORDER_LIST_SUCCESS';
export const FETCH_ORDER_LIST_FAILED = 'FETCH_ORDER_LIST_FAILED';

export const REQUEST_CHECKOUT = 'REQUEST_CHECKOUT';
export const REQUEST_CHECKOUT_SUCCESS = 'REQUEST_CHECKOUT_SUCCESS';
export const REQUEST_CHECKOUT_FAILED = 'REQUEST_CHECKOUT_FAILED';
